### ISSUE TITLE
Building on linux (for linux)?

### ISSUE THREAD

**Issue by raydeejay** [phreda4/r3d4#3]
I can't make head or tails of how to build a new r3lin. The one with the distribution segfaults with many programs, on my system at least.

**Comment by phreda4** [comment]
Hi Ray, I guess some words  use 64 bit address and then crash (in raspberry for example, this happens), if you point me the crash example, I see in more deep

**Comment by raydeejay** [comment]
doomfire.r3 for example

I still would like what to replace the Windows-specific stuff in the .asm files with :-)

**Comment by phreda4** [comment]
Ok, you like to generate r3lin? o make standalone executable (comple to asm)?
for the first the repo is https://github.com/phreda4/r3vm
You can compile with make. 
For the second you need traslate https://github.com/phreda4/r3d4/blob/master/asm/r3fasm.asm 
to linux, the compiler generate OS independent code, only call to this rutines.. I try in the past but I can't run a  SDL2 example in fasm over linux..

**Comment by raydeejay** [comment]
> Ok, you like to generate r3lin? o make standalone executable (comple to asm)?

Probably both, but right now just generate r3lin. I'll fetch that repo :-)

**Comment by raydeejay** [comment]
The version I just compiled runs doomfire.r3 just fine, I'm going to toy with the rest now :-D
